name: deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: test1
      run: python --version
    - name: test2
      run: python3 --version
    - name: apt
      run: sudo apt-get update
    - name: setuptools
      run: sudo apt-get install python3-setuptools
    - name: setup
      run: pip3 install -r requirements.txt
    - name: run
      run: make
