name: deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: python2 version
      run: python --version
    - name: python3 version
      run: python3 --version
    - name: apt
      run: sudo apt-get update
    - name: pip base install
      run: |
        pip install wheel
    - name: setup
      run: pip install -r requirements.txt
    - name: run
      run: make
